docs/CHANGELOG.md
gcdt/gcdt_logging.py
infrastructure/jenkins/jobs/gcdt_develop.groovy
infrastructure/jenkins/jobs/gcdt_pull_request.groovy

#213 getLogger helper to be used by gcdt-plugins

---

docs/CHANGELOG.md

#285 improve exception handling + proper error message for missing conf

---

.gitignore
docs/40_ramuda.md
docs/CHANGELOG.md
gcdt/gcdt_defaults.py
gcdt/gcdt_logging.py
gcdt/ramuda_main.py
gcdt_testtools/helpers.py
infrastructure/jenkins/scripts/gcdt_lifecycle.sh
requirements.txt
tests/resources/sample_lambda_nodejs/package.json
tests/test_ramuda.py
tests/test_ramuda_aws.py
tests/test_ramuda_main.py
tests/test_tenkai_aws.py
tests/test_tenkai_main.py

#254 new bundler with nodejs6.10 support

---

.gitignore
docs/CHANGELOG.md
gcdt/ramuda_core.py
gcdt/ramuda_main.py
infrastructure/jenkins/scripts/gcdt_lifecycle.sh

Gcdt version2

---

README.md
docs/07_installation.md
docs/gcdt_plugins/10_overview.md
gcdt/gcdt_defaults.py
gcdt/gcdt_lifecycle.py
infrastructure/jenkins/scripts/gcdt_lifecycle.sh
requirements.txt
requirements_dev.txt

#280 use default config from gcdt_defaults

---

README.md
docs/30_tenkai.md
docs/CHANGELOG.md
gcdt/gcdt_defaults.py

#266 add stack_output.yml to bundle artifact

---

docs/CHANGELOG.md
gcdt/kumo_core.py
gcdt/kumo_main.py
tests/test_kumo_aws.py

#64 fix kumo parameter diffing

---

docs/CHANGELOG.md
gcdt/tenkai_main.py

#60 tenkai clean up /tmp files

---

docs/70_development.md
docs/CHANGELOG.md
gcdt/ramuda_core.py
gcdt/servicediscovery.py
gcdt_testtools/placebo_awsclient.py
requirements.txt
requirements_dev.txt

#226 fix datetime handling

---

docs/CHANGELOG.md
gcdt/kumo_core.py
tests/test_kumo.py

#292 [kumo] Ignoring of artifactBucket param not working

---

docs/40_ramuda.md
docs/CHANGELOG.md
gcdt/ramuda_core.py
gcdt_testtools/helpers_aws.py
tests/test_ramuda_aws.py

#145 fix ramuda re-deploys version even without changes issue

---

docs/CHANGELOG.md
gcdt/utils.py

#40 define GracefulExit exception

---

docs/20_kumo.md
docs/CHANGELOG.md

This is just a small documentation update for kumo
To consider:
* Is this feature suitable for gcdt or better a gcdt-plugin
* Does this feature have test coverage? (see docs for info about tests)
* Backwards compatibility
* #305
External PR | [title](https://github.com/glomex/gcdt/)
By submitting a pull request to gcdt you agree to this Contributor License Agreement, you are waiving your rights to the …

minor kumo documentation updates

---

docs/CHANGELOG.md
gcdt/utils.py

#313 do not fail check_gcdt_update when PyPi is down

---

docs/07_installation.md
docs/CHANGELOG.md
gcdt/kumo_core.py

added installation documentation

---

docs/40_ramuda.md
docs/CHANGELOG.md
docs/todo.txt

few tiny ramuda docu improvements (json format for samples)

---

docs/07_installation.md
docs/CHANGELOG.md
docs/gcdt_plugins/15_plugin_mechanism.md
docs/gcdt_plugins/20_config.md
docs/index.rst

A few sentences describing the overall goals of the pull request's commits / links to relevant github issues.
To consider:
* Is this feature suitable for gcdt or better a gcdt-plugin
* Does this feature have test coverage? (see docs for info about tests)
* Backwards compatibility
Are there any other PR's on which this depends?
External PR | [title](https://github.com/glomex/gcdt/)
By submitting a pull request to …

Add getting started guide into index.rst. Fix images. Add changelog

---

docs/CHANGELOG.md
gcdt/kumo_core.py

#126 [kumo] add status message for empty changeset

---

docs/CHANGELOG.md
requirements.txt
requirements_dev.txt

#285 fix deps

---

docs/CHANGELOG.md
gcdt/utils.py

#337 fix warning message

---

docs/CHANGELOG.md
gcdt/gcdt_lifecycle.py
tests/test_gcdt_lifecycle.py
tests/test_gcdt_livecycle.py

#348 report correct deployment status on slack

---

docs/50_yugen.md
docs/CHANGELOG.md
gcdt/yugen_core.py
gcdt/yugen_main.py
tests/test_yugen_aws.py

#328 yugen: cacheClusterEnabled setting

---

docs/CHANGELOG.md
gcdt/kumo_core.py

#357 fix kumo template error in update case

---

docs/50_yugen.md
docs/CHANGELOG.md
gcdt/servicediscovery.py
gcdt/yugen_core.py
gcdt/yugen_main.py
tests/resources/sample_api_with_caching/api_dev.conf
tests/resources/sample_api_with_caching/apikey.txt
tests/resources/sample_api_with_caching/requirements.txt
tests/resources/sample_api_with_caching/swagger.yaml
tests/test_yugen.py

#328 yugen: implement cache settings on method level

---

docs/50_yugen.md
docs/CHANGELOG.md
gcdt/yugen_core.py

#328 yugen: default value for cache size property

---

gcdt/event_source/__init__.py
gcdt/event_source/cloudfront.py
gcdt/gcdt_awsclient.py
gcdt/gcdt_exceptions.py
gcdt/ramuda_utils.py
gcdt/ramuda_wire.py
gcdt/utils.py
tests/resources/sample_lambda_edge/gcdt_dev.json
tests/resources/sample_lambda_edge/index.html
tests/resources/sample_lambda_edge/index.js
tests/resources/sample_lambda_edge/package.json

#381 lambda@edge event source for ramuda wiring

---

CHANGELOG.md
gcdt/gcdt_awsclient.py
infrastructure/jenkins/scripts/gcdt_lifecycle.sh
requirements.txt
requirements_dev.txt

#379 set botocore user agent

---

CHANGELOG.md
gcdt/gcdt_defaults.py
gcdt/kumo_core.py
gcdt/kumo_main.py

#355 kumo info command

---

gcdt/gcdt_defaults.py
tests/test_ramuda_aws.py

A few sentences describing the overall goals of the pull request's commits / links to relevant github issues.
To consider:
* Is this feature suitable for gcdt or better a gcdt-plugin
* Does this feature have test coverage? (see docs for info about tests)
* Backwards compatibility
Are there any other PR's on which this depends?
External PR | [title](https://github.com/glomex/gcdt/)
By submitting a pull request to …

Added nodejs8.10 support
